---
- name: Put fqdn to /etc/hostname
  copy: dest=/etc/hostname content={{ fqdn }}

- name: Set Hostname with hostname command
  hostname: "{{ hostname }}"

- name: Re-gather facts
  action: setup
  when: ansible_hostname != fqdn

# Idempotent way to build a /etc/hosts file with Ansible using your Ansible hosts inventory for a source.
# Will include all hosts the playbook is run on.
# Credits to rothgar: https://gist.github.com/rothgar/8793800
- name: Build hosts file (backups will be made)
  lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line='{{ hostvars[item].ansible_default_ipv4.address }} {{ fqdn }} {{ hostname }}' state=present backup=yes
  when: hostvars[item].ansible_default_ipv4.address is defined
  with_items: groups['all']
